---
- hosts: localhost
  become: yes
  
  tasks:
    - name: install nfs-kernel-server
      apt: name=nfs-kernel-server state=latest

    
    - name: Create a mountable directory if it does not exist
      file:
        path: /home/dorian/nfs_test
        state: directory
        owner: dorian
        group: dorian
        mode: '0775'

    

    - name: enable rpcbind nfs-server nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs idmap
      when: inventory_hostname == "storage"

    

    - name: Copy exports file.
      template:
        src: "exports.j2"
        dest: "/etc/exports"
        owner: root
        group: root
        mode: 0644
    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a